apiVersion: v1
kind: Service
metadata:
  name: json-server-service
  namespace: json-server  
spec:
  selector:
    app: json-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
